name: Build & Deploy All (Build + Test + Build & Push Containers)

on:
  workflow_dispatch:
    inputs:
      teamName:
        description: 'Team name (e.g. team1)'
        required: true
        default: 'team1'

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push_all_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # ------------------------------------------------------
      # (1) Restore, Build & Test Survey-App (.NET Blazor)
      # ------------------------------------------------------
      - name: Restore & Build Survey-App
        working-directory: src/Survey-App
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Run Survey-Tests
        working-directory: tests/Survey-Tests
        run: |
          dotnet restore
          dotnet test --no-build --verbosity normal

      # ----------------------------------------------------------
      # (2) Restore, Build & Test Reporting-App (.NET Blazor)
      # ----------------------------------------------------------
      - name: Restore & Build Reporting-App
        working-directory: src/Reporting-App
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Run Reporting-Tests
        working-directory: tests/Reporting-Tests
        run: |
          dotnet restore
          dotnet test --no-build --verbosity normal

      # ---------------------------------------------------------------------
      # (3) Build & Push Survey-App Container using docker/build-push-action
      # ---------------------------------------------------------------------
      - name: Build & Push Survey-App Image
        id: push_survey
        uses: docker/build-push-action@v6
        with:
          context: src/Survey-App
          file: src/Survey-App/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/survey-app-${{ github.event.inputs.teamName }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/survey-app-${{ github.event.inputs.teamName }}:${{ github.ref_name || github.head_ref }}
          build-args: |
            NUGET_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
            USERNAME=${{ github.actor }}
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}

      # -------------------------------------------------------------------------
      # (4) Build & Push Reporting-App Container using docker/build-push-action
      # -------------------------------------------------------------------------
      - name: Build & Push Reporting-App Image
        id: push_reporting
        uses: docker/build-push-action@v6
        with:
          context: src/Reporting-App
          file: src/Reporting-App/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/reporting-app-${{ github.event.inputs.teamName }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/reporting-app-${{ github.event.inputs.teamName }}:${{ github.ref_name || github.head_ref }}
          build-args: |
            NUGET_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
            USERNAME=${{ github.actor }}
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}