name: Build & Deploy All

on:
  workflow_dispatch:
    inputs:
      teamName:
        description: 'Team Name (IMPORTANT)'
        default: 'default-team'

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push_all_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # ------------------------------------------------------
      # (0) Lower-case the repo owner for Docker tags
      # ------------------------------------------------------
      - name: Lower-case the repo owner
        shell: bash
        run: |
          echo "OWNER_LOWER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      # ------------------------------------------------------
      # (1) Restore, Build & Test Survey-App (.NET Blazor)
      # ------------------------------------------------------
      - name: Restore & Build Survey-App
        working-directory: src/Survey-App
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Run Survey-Tests
        working-directory: tests/Survey-Tests
        run: |
          dotnet restore
          dotnet test --verbosity normal

      # ----------------------------------------------------------
      # (2) Restore, Build & Test Reporting-App (.NET Blazor)
      # ----------------------------------------------------------
      - name: Restore & Build Reporting-App
        working-directory: src/Reporting-App
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Run Reporting-Tests
        working-directory: tests/Reporting-Tests
        run: |
          dotnet restore
          dotnet test --verbosity normal

      # ---------------------------------------------------------------------
      # (3) Build & Push Survey-App Container using docker/build-push-action
      # ---------------------------------------------------------------------
      - name: Build & Push Survey-App Image
        id: push_survey
        uses: docker/build-push-action@v6
        with:
          context: src/Survey-App
          file: src/Survey-App/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LOWER }}/survey-app-${{ github.event.inputs.teamName }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.OWNER_LOWER }}/survey-app-${{ github.event.inputs.teamName }}:${{ github.ref_name || github.head_ref }}
          build-args: |
            NUGET_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
            USERNAME=${{ github.actor }}
          secrets: |
            github_token=${{ secrets.GHCR_PAT }}

      # -------------------------------------------------------------------------
      # (4) Build & Push Reporting-App Container using docker/build-push-action
      # -------------------------------------------------------------------------
      - name: Build & Push Reporting-App Image
        id: push_reporting
        uses: docker/build-push-action@v6
        with:
          context: src/Reporting-App
          file: src/Reporting-App/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LOWER }}/reporting-app-${{ github.event.inputs.teamName }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.OWNER_LOWER }}/reporting-app-${{ github.event.inputs.teamName }}:${{ github.ref_name || github.head_ref }}
          build-args: |
            NUGET_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
            USERNAME=${{ github.actor }}
          secrets: |
            github_token=${{ secrets.GHCR_PAT }}